name: ovu_application
description: OVU Project

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  sizer: ^2.0.15
  get_storage: ^2.0.3
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.11.0
  flutter_multi_formatter: ^2.10.0
  pin_code_fields: ^7.4.0
  table_calendar: ^3.0.8
  flutter_staggered_grid_view: ^0.4.1
  transparent_image: ^2.0.0
  flutter_calendar_week: ^3.0.0
  gradient_borders: ^0.2.0
  percent_indicator: ^4.2.2
  arabic_numbers: ^1.0.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/badges/
    - assets/icons/
    - assets/products_images/

  fonts:
    - family: Teshrin
      fonts:
        - asset: assets/fonts/Teshrin AR LT Bold.ttf
        - asset: assets/fonts/Teshrin AR LT Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf  
